development:
  clients:
    default:
      database: resize_photos_challenge_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: resize_photos_challenge_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
